
name: "kitti"
labels: 
  0 : "unlabeled"
  1 : "outlier"
  9 : "static"     # for lidar-mos static 
  10: "car"
  99: "other-object"
  251: "moving"      # lidar-mos moving
  252: "moving-car"
color_map: # bgr
  0 : [0, 0, 0]
  1 : [0, 0, 0]  # [0, 0, 255] 
  9 : [0, 0, 0]     # for lidar-mos static
  10: [245, 150, 100]
  99: [255, 255, 50]
  251: [0, 0, 255]  # lidar-mos moving
  252: [245, 150, 100]
content: # as a ratio with the total number of points
  0: 0
  10: 0
  99: 0.992517993
  252: 0.0074820062
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent
learning_map:
  0 : 0     # "unlabeled"       mapped to "unlabeled" ------------------------mapped
  1 : 0     # "outlier"         mapped to "unlabeled" ------------------------mapped
  9 : 1     # "static"          mapped to "static" ---------------------------mapped
  10: 2     # "car"             mapped to "static" ---------------------------mapped
  99: 1     # "other-object"    mapped to "static" ---------------------------mapped
  251: 2    # "moving"              mapped to "moving" ---------------------------mapped
  252: 2    # "moving-car"          mapped to "moving" ---------------------------mapped
learning_map_inv: # inverse of previous map
  0: 0      # "unlabeled", and others ignored
  1: 9      # "static"
  2: 251    # "moving"

learning_ignore: # Ignore classes
  0: True      # "unlabeled", and others ignored
  1: False     # "static"
  2: False     # "moving"